---
title: "EDA time series"
output: html_document
date: "`r Sys.Date()`"
params:
  dm: dm
  data_tbl: data_tbl
  year: year
editor_options: 
  chunk_output_type: console
---

```{r include=FALSE}
library(tidyverse)
pkgload::load_all()
knitr::opts_chunk$set(echo = FALSE, cache = TRUE, fig.align = "center", message = FALSE, warning = FALSE, fig.height = 8)
```

```{r echo=FALSE}
dm <- params$dm
data_tbl <- params$data_tbl
```

```{r}
tbl <-
  prep_tb_data(data_tbl, e_inc_num, c_newinc, "country_code") |> 
  mutate(xpert = coalesce(xpert, m_wrd)) |>
  select(-c(m_wrd, c_newinc, e_inc_num, country_code))

all_indicators_df <-
  data_tbl |>
  compute_dx_gap(e_inc_num, c_newinc) |>
  mutate(is_hbc = forcats::as_factor(is_hbc)) |>
  mutate(xpert = coalesce(xpert, m_wrd)) |>
  select(-m_wrd)
```

```{r fig.height=8}
# Q: how does dx gap vary over time for each hb country_code?
all_indicators_df |>
  filter(is_hbc == 1) |>
  select(country_code, dx_gap, year) |>
  ggplot(aes(x = year, y = dx_gap)) +
  geom_line(colour = "#1f65b7", linewidth = 1) +
  facet_wrap(vars(country_code), ncol = 3) +
  scale_y_continuous(labels = scales::label_percent(scale = 1)) +
  scale_x_continuous(
    breaks = seq(
      min(all_indicators_df$year), 
      max(all_indicators_df$year), 
      by = 2
    )
  ) +
  theme_minimal() +
  labs(
    title = "The DX Gaps in high burden countries vary differently over time",
    x = NULL, y = "DX Gap"
  )
```

```{r}
# Q: how does dx gap vary over time on average?
all_indicators_df |>
  summarise(mean_dx_gap = mean(dx_gap), .by = c(is_hbc, year)) |>
  ggplot(aes(x = year, y = mean_dx_gap, colour = is_hbc)) +
  geom_line(linewidth = 1) +
  geom_text(
    data = . %>% filter(year == max(year)), 
    aes(label = ifelse(is_hbc == 1, "High burden", "Low burden")), 
    hjust = 1,
    vjust = -1
  ) +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(
    title = "The DX Gap over time demonstrates no seasonality/stationarity",
    subtitle = "A simple time series model should be tested",
    x = NULL,
    y = "Mean TB DX Gap"
  ) +
  scale_colour_viridis_d(
    alpha = 1,
    begin = .2,
    end = .8,
    direction = -1,
    option = "A",
    aesthetics = "colour"
  ) +
  # Set to zero show magnitude of relevant difference
  scale_y_continuous(limits = c(0, NA), labels = scales::label_percent(scale = 1)) + 
  scale_x_continuous(
    limits = c(min(all_indicators_df$year), max(all_indicators_df$year) + .25)
  )
```

```{r}
# Q: how do the predictor variables vary over time on average for HBC?
all_indicators_df |>
  filter(is_hbc == 1) |>
  select(-c(is_hbc, country_code, dx_gap)) |>
  pivot_longer(!year) |>
  summarise(mean_value = mean(value, na.rm = TRUE), .by = c(year, name)) |>
  ggplot(aes(x = year, y = mean_value)) +
  facet_wrap(vars(name), scales = "free_y", ncol = 3) +
  geom_line(linewidth = 1, colour = "#1f65b7") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_y_continuous(labels = scales::label_number(big.mark = "'")) +
  labs(
    title = "How do predictors change, on average?",
    x = NULL,
    y = "Mean"
  )
```


```{r fig.height=10}
# Q: how does each test type vary over time for each hb country_code?
all_indicators_df |>
  filter(is_hbc == 1) |>
  select(country_code, year, culture, smear, xpert) |>
  pivot_longer(!c(country_code, year)) |>
  ggplot(aes(x = year, y = value, colour = name)) +
  geom_line(linewidth = 1) +
  facet_wrap(vars(country_code), scales = "free_y", ncol = 3) +
  scale_y_log10(labels = scales::label_log(digits = 2)) +
  scale_x_continuous(
    breaks = seq(
      min(all_indicators_df$year), 
      max(all_indicators_df$year), 
      by = 2
    )
  ) +
  theme_minimal() +
  theme(
    legend.position = "top", 
    legend.title = element_blank(),
    axis.text.y = element_text(size = rel(0.7))
  ) + 
  scale_colour_viridis_d(
    alpha = 1,
    begin = .2,
    end = .8,
    direction = 1,
    option = "A",
    aesthetics = "colour"
  ) +
  labs(
    title = "Test types in most high burden countries have remained largely constant.",
    subtitle = "However, few notable exceptions such as China and Zambia are found",
    x = NULL, 
    y = NULL
  )
```

```{r}
# Q: How does test type correlate with dx gap across all time points?
corr_df_1 <- compute_correlation(tbl, dx_gap, by = "year")
```


```{r}
corr_df <- compute_correlation(tbl, dx_gap, by = c("is_hbc", "year"))
```

```{r}
corr_df |>
  mutate(is_hbc = if_else(is_hbc == 1, "High burden", "Low burden")) |> 
  ggplot(aes(year, dx_gap, group = term, color = term)) +
  geom_line() +
  scale_y_continuous(limits = c(-1, 1)) +
  theme_minimal() +
  theme(legend.title = element_blank()) +
  theme(legend.position = "top") + 
  labs(
    title = "Correlation with Dx Gap has remained largely constant.",
    subtitle = "Covid effect in 2020?",
    x = NULL,
    y = NULL
  ) +
  facet_wrap(vars(is_hbc))
```

```{r eval=FALSE}
corr_df |>
  pivot_wider(names_from = year, values_from = dx_gap) |>
  gt::gt(groupname_col = "is_hbc") |>
  gt::data_color(
    columns = dplyr::where(is.numeric),
    method = "numeric",
    palette = "Greys",
    na_color = "#ffcccb"
  )
```

```{r fig.width=12}
# Is time a signficant predictor of DX Gap in HBC?
# dx_gap = (tb_estimated_cases - tb_notified_cases) / tb_estimated_cases
# As estimated and notified cases are included as part of the calculation of
# the dx gap, the following variable are removed:
#   - c_newinc = Total of new and relapse cases and cases with unknown previous TB treatment history
#   - e_inc_num = Estimated number of incident cases
ts_model_prep <-
  all_indicators_df |>
  filter(is_hbc == 1) |>
  select(-is_hbc, -country_code, -c_newinc, -e_inc_num,) |>
  mutate(dummy = 1) %>%
  pivot_wider(names_from = year, values_from = dummy, values_fill = 0) |>
  select(-`2016`) # create reference category

ts_model_lm <-
  ts_model_prep |>
  lm(formula = dx_gap ~ .)

# Result: no determinants detected
ts_model_lm |>
  broom::tidy() |> 
  mutate_is_significant(threshold = 0.05) |> 
  mutate(is_under_0.05 = forcats::fct_relevel(is_under_0.05, c("TRUE", "FALSE"))) |> 
  mutate(term = forcats::fct_relevel(term, sort)) |> 
  plot_coeff_table()
```

```{r}
# Check for multicollinearity (VIF)
# Result: there is high multicollinearity across many predictors that would need
# resolving
check_vif <- performance::check_collinearity(ts_model_lm)
plot(check_vif) +
  theme(axis.text.x = element_text(angle = 90))
```

```{r eval=FALSE}
# Stepwise regression to optimise model (is this valid for statistical
# inference? Are assumptions not violated?)
# https://otexts.com/fpp3/selecting-predictors.html#beware-of-inference-after-selecting-predictors
step(ts_model_lm)
```
