skip_if(Sys.getenv("DXGAP_DATADIR") == "")
data_list <- load_dx("tb")
dm <- build_dm(data_list, year = 2019)
tbl <- build_tbl(dm)
test_that("compute_completion_rate() works", {
  complete_rate_df_country <- compute_completion_rate(tbl, id_vars = "year")
  expect_snapshot(constructive::construct(complete_rate_df_country))
  complete_rate_df_is_hbc <- compute_completion_rate(tbl, id_vars = c("year", "is_hbc"))
  expect_snapshot(constructive::construct(complete_rate_df_is_hbc))
  cars_df <- tibble::as_tibble(mtcars, rownames = "car_name")
  complete_rate_df_cars <- compute_completion_rate(cars_df, id_vars = NULL)
  expect_snapshot(constructive::construct(complete_rate_df_cars))
})
