dxgap_constants <- tibble::lst(
  start_year = 2015,
  tb_vars = c("year",
              "country",
              "is_hbc",
              "country_code",
              "who_dx_gap",
              "pop_total",
              "pop_urban_perc",
              "pop_density",
              "gdp",
              "c_newinc",
              "e_inc_num",
              "e_mort_100k",
              "culture",
              "smear",
              "xpert",
              "m_wrd")
)


tb_constants <- tibble::lst(
  country = c(
    "Angola",
    "Bangladesh",
    "Brazil",
    "Cambodia",
    "Central African Republic",
    "China",
    "Congo",
    "Democratic People's Republic of Korea",
    "DRC",
    "Ethiopia",
    "India",
    "Indonesia",
    "Kenya",
    "Lesotho",
    "Liberia",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nigeria",
    "Pakistan",
    "Papua New Guinea",
    "Philippines",
    "Russian Federation",
    "Sierra Leone",
    "South Africa",
    "Thailand",
    "United Republic of Tanzania",
    "Viet Nam",
    "Zambia",
    "Zimbabwe"
  ),
  indicator_ts = c(
    "tb_incidence_per_100k",
    "population_100k",
    "rate_tb_case_detection",
    "rate_bacteriologically_tested",
    "labs_performing_smear_tests",
    "labs_performing_xpert_tests",
    "labs_performing_culutre_tests_liquid",
    "labs_performing_dst"
  )
)
